### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by sijangurung** [gt-theamiri/gmailClone#1]
![Simulator Screen Shot - iPhone X - 2020-05-04 at 11 08 45](https://user-images.githubusercontent.com/4437358/80951192-b0bf7f80-8df7-11ea-815b-868e573a9745.png)

**Comment by sijangurung** [comment]
Use :
[ primary_section.dart : 87]
subtitle.length > 28
                        ? '${subtitle.replaceRange(28, subtitle.length, "...")}'
                        : subtitle,
[ inbox_section.dart : 115]
                  (content.length > 28)
                      ? content.replaceRange(28, content.length, "...")
                      : content,
or, check mediaQuery and make width dynamic according to size.width

**Comment by gt-theamiri** [comment]
i apply changes to main Container by setting it's width and height to max infinite
